#!/usr/bin/env bash

# Get public IP
sudo iptables -L > teee.txt
cat teee.txt
#INTERF=$(ifconfig)
echo "ifconfig ifconfig ifconfig ifconfig"
ip link add wg0 type wireguard
ifconfig
#echo $INTERF
#systemctl sshd status

